dist: xenial

language: python
python:
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    packages:
      - portaudio19-dev

install:
  - pip3 install pylint
  - pip3 install -r requirements.txt

script:
  - pylint -E src
  - pylint -E bin
